services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    environment:
      RAILS_ENV: production
      DATABASE_URL: mysql2://pragma2_prd:${P2_DATABASE_PASSWORD}@104.197.173.67:3306/pragma2_prd
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "127.0.0.1:3000:3000"
