default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 104.197.173.67
  port: 3306

development:
  <<: *default
  database: pragma2_prd
  username: pragma2_prd
  password: <%= ENV.fetch("P2_DATABASE_PASSWORD", "") %>

test:
  <<: *default
  database: pragma2_prd
  username: pragma2_prd
  password: <%= ENV.fetch("P2_DATABASE_PASSWORD", "") %>

production:
  <<: *default
  database: pragma2_prd
  username: pragma2_prd
  password: <%= ENV["P2_DATABASE_PASSWORD"] %>
